<?php
    $query_abajo="SELECT d.dia,
    COALESCE(SUM(v.total), 0) AS dinero_total
    FROM (
        -- genera los días del 1 al último del mes actual
        SELECT DATE_ADD(DATE_FORMAT(CURDATE(),'%Y-%m-01'), INTERVAL n DAY) AS dia
        FROM (
            SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
            UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
            UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
            UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
            UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24
            UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29
            UNION ALL SELECT 30
        ) numbers
        WHERE DATE_ADD(DATE_FORMAT(CURDATE(),'%Y-%m-01'), INTERVAL n DAY) <= LAST_DAY(CURDATE())
    ) d
    LEFT JOIN docventa v ON DATE(v.fecha) = d.dia
    GROUP BY d.dia
    ORDER BY d.dia;"
?>